version: 1.0.{build}
image: Visual Studio 2017

install:
  - curl.exe -Lo "C:\Program Files\docker\dockerd.exe" https://master.dockerproject.com/windows/x86_64/dockerd.exe
  - set PATH=c:\program files\docker;%PATH%
  - sc stop com.docker.service
#  - choco install -y vagrant

build: off

test_script:
#  - vagrant validate
  - ps: .\scripts\create-machine.ps1 -machineHome C:/Users/foo -machineName 2016
